stages:
  - build
  - test

build_job:
  stage: build
  script:
    - ./gradlew bootJar
  image: gradle:7-jdk17-alpine
  artifacts:
    name: RewardService_build_artifact
    paths:
      - build/libs/*.jar
      - Dockerfile

test_job:
  stage: test
  script:
    - ./gradlew test
  image: gradle:7-jdk17-alpine
  artifacts:
    name: Reports_artifact
    paths:
      - build/reports/tests/test
      - build/reports/jacoco/test/html